#!/usr/bin/env python3
import G4GeoLoki.LokiAimHelper as LokiAim
import argparse

parser = argparse.ArgumentParser(description = 'Exporting 3D pixel positions of the LOKI detector array based on the Geant4 geometry. The resulting file is a csv file with the following columns: pixelId, pixelCentreX [m], pixelCentreY [m], pixelCentreZ [m]. Axes represent the beam\'s point of view: X - horizontal (positive to the left), Y - vertical (positive up), Z - distance along the beam (by default distance from the sample position).')
parser.add_argument('-f', '--fileName', default='LokiPixelFile', help = 'Output file name (.txt appended)')
parser.add_argument('-rear', '--rearDetectorDistance', type=float, default=5.0, help = 'Rear detector distance [m] (defaults to 5 m)')
parser.add_argument('-ssd', '--sourceSampleDistance', type=float, default=0.0, help = 'Source sample distance [m] (defaults to 0 m)')
parser.add_argument('-n', '--strawPixelNumber', type=int, help = 'Rear detector pixel number (defaults to the value defined in the PixelatedBanks class)')
parser.add_argument('--bankId', type=int, default=None, help = 'Provide bank id [0,8] to output pixels only for the selected bank. Default is to output info for all banks.')
parser.add_argument('--print', action = 'store_true', help = 'Print pixel positions to output insted of a file.')
parser.add_argument('--bankCalibration', default=None, help = f'Bank placements (the bank_calibration geometry parameter): {LokiAim.NOMINAL_BANK_CALIBRATION}, the name of a bank calibration in G4GeoLoki/data (bank_calibration_<name>.txt) or the path of such a file. Default: {LokiAim.DEFAULT_BANK_CALIBRATION}.')

args = parser.parse_args()

rearBankDistance = args.rearDetectorDistance
strawPixelNumber = args.strawPixelNumber if args.strawPixelNumber is not None else LokiAim.DEFAULT_NUMBER_OF_PIXELS_IN_STRAW
bankCalibration = args.bankCalibration if args.bankCalibration is not None else LokiAim.DEFAULT_BANK_CALIBRATION
aimHelper = LokiAim.AimHelper(rearBankDistance * 1000, strawPixelNumber, 9, bankCalibration)

ssd = args.sourceSampleDistance

fileName = f"{args.fileName}.txt"
with open(fileName, "w") as pixelFile:
  if args.bankId is not None:
    pixelMin = aimHelper.getBankPixelOffset(args.bankId)
    pixelMax = aimHelper.getBankPixelOffset(args.bankId + 1)
  else:
    pixelMin = 0
    pixelMax = aimHelper.getTotalNumberOfPixels()

  for pixelId in range(pixelMin, pixelMax):
    pixelCentreX, pixelCentreY, pixelCentreZ = aimHelper.getPixelCentreCoordinates(pixelId)
    pixelCentreZ = pixelCentreZ + ssd *1000

    # +1: the detector ids in the IDF (and ICD) file start from 1 (the pixel ids of the Geant4 geometry from 0)
    pixelFile.write( f"{pixelId + 1}, {pixelCentreX/1000:.4f}, {pixelCentreY/1000:.4f}, {pixelCentreZ/1000:.4f}\n")


if not args.print:
  print(f"File created: {fileName}")
else:
  with open(fileName, 'r') as f:
    print(f.read().strip())
