#!/usr/bin/env bash

ARGS="det_only=true"
sb_larmor_sim_2020 $ARGS -lPL_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    sb_larmor_ana_2020_det larmor_CountingGas_Converter.griff
else
    exit 1
fi
