#!/usr/bin/env bash

ARGS="rear_detector_distance_m=4.099 analysis_straw_pixel_number=512 beamstop_id=0 event_gen=flood gen_x_offset_meters=0.005 nominal_source_sample_distance_meters=25.61"
sb_larmor_sim_2022 $ARGS -lPL_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    sb_larmor_ana_2022 lokisim.griff
else
    exit 1
fi
