#!/usr/bin/env bash

ARGS="rear_detector_distance_m=4.099 aiming_straw_pixel_number=1024 analysis_straw_pixel_number=512 beamstop_id=0 gen_x_offset_meters=0.005"
sb_larmor_masking_sim_2022 $ARGS -lPL_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    sb_larmor_masking_ana_2022 loki_masking.griff
else
    exit 1
fi
