#!/usr/bin/env bash

ARGS="rear_detector_distance_m=5 aiming_straw_pixel_number=1024 analysis_straw_pixel_number=512 beamstop_id=0 with_calibration_slits=True"
sb_lokimasking_sim $ARGS -lPL_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    sb_lokimasking_ana loki_masking.griff
else
    exit 1
fi
