#!/bin/bash

ARGS="rear_detector_distance_m=10 aiming_straw_pixel_number=32 analysis_straw_pixel_number=64 with_beamstop=False"
ess_lokimasking_sim $ARGS -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_lokimasking_ana loki_masking.griff
else
    exit 1
fi
