#!/usr/bin/env bash

ARGS="rear_detector_distance_m=4.099 aiming_straw_pixel_number=2048 analysis_straw_pixel_number=512 beamstop_id=0 larmor_2022_experiment=True with_calibration_slits=True gen_x_offset_meters=0.005"
sb_lokimasking_sim $ARGS -lPL_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    sb_lokimasking_ana_larmor2022 loki_masking.griff
else
    exit 1
fi
