#!/bin/bash

ARGS="rear_detector_distance_m=5 aiming_straw_pixel_number=1024 analysis_straw_pixel_number=512 rear_detector_only=False with_beamstop=False with_calibration_slits=True"
ess_lokimasking_sim $ARGS -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_lokimasking_ana loki_masking.griff
else
    exit 1
fi
