#!/usr/bin/env bash

MCPLFILE=`sb_core_finddata LokiMantid detectionEventsFlood_testFile.mcpl`

cmdArgs=('--' $MCPLFILE '--neutronNumber=25' '--analysis_straw_pixel_number=256' '--noOutput')

#Test mantidpython (python vs ipython) to see whether '--' is needed before the arguments
if ! sb_lokimantid_larmor2022 -- -h ; then
  unset cmdArgs[0]
fi
sb_lokimantid_larmor2022 "${cmdArgs[@]}"
