#!/usr/bin/env bash

ess_loki_sim event_gen=flood -n25 analysis_straw_pixel_number=2 |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_loki_ana lokisim.griff
else
    exit 1
fi

# only testing the full workflow (sim-ana-processing), but not the results
cmdArgs=('--' 'detectionEvents.mcpl' '--savename=test' '--neutronNumber=25')

#Test mantidpython (python vs ipython) to see whether '--' is needed before the arguments
if ! ess_lokimantid_loki -- -h ; then
  unset cmdArgs[0]
fi
G4PROC_MCPL_BASEDIR_LOKI=./ G4PROC_SAVEDIR_LOKI=./ ess_lokimantid_loki "${cmdArgs[@]}"
