#!/usr/bin/env bash

# testing the processing of an already existing mcpl file (backward compatibility)
MCPLFILE=`sb_core_finddata LokiMantid detectionEventsFlood_testFile.mcpl`

cmdArgs=('--' $MCPLFILE '--neutronNumber=25' '--analysis_straw_pixel_number=4' '--singleNexus' '--noOutput')

#Test mantidpython (python vs ipython) to see whether '--' is needed before the arguments
if ! sb_lokimantid_loki -- -h ; then
  unset cmdArgs[0]
fi
sb_lokimantid_loki "${cmdArgs[@]}"
