#!/usr/bin/env bash

ess_loki_sim event_gen=flood -n25 analysis_straw_pixel_number=2 |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_loki_ana lokisim.griff
else
    exit 1
fi

# only testing the full workflow (sim-ana-processing), but not the results
G4PROC_MCPL_BASEDIR_LOKI=./ G4PROC_SAVEDIR_LOKI=./ ess_lokimantid_loki -- detectionEvents.mcpl --savename=test --neutronNumber=25