name: Call test workflow

on:
  push:
  schedule:
    - cron: '30 23 * * 0'  # 23:30 every Sunday
  workflow_dispatch:

jobs:
  use-test-workflow:
    uses: mctools/dgcode_actions/.github/workflows/run_tests.yml@main
    with:
      pkg-repo: ess-dg/dgcode_projects
      pkg-repo-branch: '${{ github.ref_name }}'
      dgcode-branch: main
      setup-choice: defaults
