#!/bin/bash

ARGS="rear_detector_distance_m=4.099 analysis_straw_pixel_number=512 with_beamstop=False larmor_2022_experiment=True event_gen=flood gen_x_offset_meters=0.005 nominal_source_sample_distance_meters=25.61"
ess_loki_sim $ARGS -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_loki_ana_larmor2022 lokisim.griff
else
    exit 1
fi
