#!/bin/bash

ARGS="rear_detector_distance_m=10 aiming_straw_pixel_number=32 analysis_straw_pixel_number=64 with_beamstop=False event_gen=masking"
ess_loki_sim $ARGS -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_loki_ana_masking lokisim.griff
else
    exit 1
fi
