#!/bin/bash

ARGS="rear_detector_distance_m=4.099 aiming_straw_pixel_number=1024 analysis_straw_pixel_number=512 rear_detector_only=True with_beamstop=False larmor_2022_experiment=True event_gen=masking gen_x_offset_meters=0.005" 
ess_loki_sim $ARGS -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_loki_ana_masking lokisim.griff
else
    exit 1
fi