#!/usr/bin/env bash

# testing full geometry (this takes long), and the flood sim-ana workflow (but not the results)
sb_loki_sim -t -lESS_Empty && \
sb_loki_sim -lESS_Empty event_gen=flood |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    sb_loki_ana lokisim.griff
else
    exit 1
fi
