#!/bin/bash

ess_loki_sim_larmor2020 -t -lESS_Empty && \
ess_loki_sim_larmor2020 gen_x_offset_meters=-0.040 cone_opening_deg=10.4753 withBeamstop=True event_gen=flood -lESS_Empty |grep '^G4Launcher::Launcher'
if [ ${PIPESTATUS[0]} == 0 ]; then
    ess_loki_ana_larmor2020 larmor.griff
else
    exit 1
fi
