#!/usr/bin/env python3

#############################################################
#Define geometry:
import G4GeoBCS.GeoBCS as geomodule
geo = geomodule.create()

#############################################################
#Define particle generation:

import BCS.Common
BCS.Common.launch(geo)
